{% set name = "minimalkv" %}
{% set version = "1.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/minimalkv-{{ version }}.tar.gz
  sha256: c877433ca4f06d1b40c36cce9b4e06ccec432606df20a9a9f9c450a9faabfa13

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - python >=3.8
    - uritools
  run_constrained:
    - gcsfs >=2022.10.0

test:
  imports:
    - minimalkv
  commands:
    - pip check
    - python -c 'from minimalkv import get_store; get_store("fs", path=".")'
    - python -c 'from minimalkv import get_store; get_store("hfs", path=".")'
  requires:
    - pip

about:
  home: https://github.com/data-engineering-collective/minimalkv
  summary: A key-value storage for binary data, support many backends.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtilly
    - fjetter
    - mlondschien
    - siboehm
    - xhochy
