{% set name = "minimalkv" %}
{% set version = "1.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/minimalkv-{{ version }}.tar.gz
  sha256: fcc441969dd2a9febefd09429ec64d377f5776faed54954adf5037f7edac4f86

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools_scm
  run:
    - python >=3.8
    - uritools
  run_constrained:
    - google-cloud-storage >=1.31.0

test:
  imports:
    - minimalkv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/data-engineering-collective/minimalkv
  summary: A key-value storage for binary data, support many backends.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtilly
    - fjetter
    - mlondschien
    - siboehm
    - xhochy
